### PR TITLE
feat: add Wasmtime example

### PR DESCRIPTION
**Pull request by maxbrunet**
Continuing with an exotic/still uncommon runtime: Rust compiled to WASM, executed with Wasmtime

https://bytecodealliance.org/articles/wasmtime-1-0-fast-safe-and-production-ready

Supports jitdump only.

image

Blocked by parca-dev/parca-agent#1051

### CODE REVIEW

**Comment by maxbrunet** [comment]
Crun, the container runtime, also has native support for WebAssembly (via `wasmtime` among other runtimes), but I have not found if it is possible to enable jitdump in this case: https://opensource.com/article/22/10/wasm-containers

**Comment by maxbrunet** [comment]
No longer blocked, parca-dev/parca-agent#1051 has been merged.

**Review by brancz — APPROVED** [review]

**Comment by brancz** [comment]
I already said on discord but wanna say here one more time. It simply feels like magic that this works!

**Review by kakkoyun — APPROVED** [review]
LGTM  ❤️ 💚 💙 💛 💜

**Pull request merged**
